### ISSUE TITLE
/obp/v2.2.0/message-docs/mar2017 gives 500 on apisandbox

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/OBP-API#470]
This works on local host /obp/v2.2.0/message-docs/mar2017

but on apisandbox.openbankproject.com it gives

HTTP ERROR 500

Problem accessing /obp/v2.2.0/message-docs/mar2017. Reason: 

    Server Error

Caused by:

java.lang.NoClassDefFoundError: Could not initialize class code.bankconnectors.KafkaMappedConnector_vMar2017$
	at code.api.v2_2_0.APIMethods220$$$$$$d07d2ec616a128522b5c4fe96ca86c0$$$$n$applyOrElse$6.apply(APIMethods220.scala:302)
	at code.api.v2_2_0.APIMethods220$$$$$$d07d2ec616a128522b5c4fe96ca86c0$$$$n$applyOrElse$6.apply(APIMethods220.scala:300)
	at code.api.OBPRestHelper$class.failIfBadAuthorizationHeader(OBPRestHelper.scala:151)
	at code.api.v2_2_0.OBPAPI2_2_0$.failIfBadAuthorizationHeader(OBPAPI2_2_0.scala:44)
	at code.api.OBPRestHelper$$anon$2.apply(OBPRestHelper.scala:196)
	at code.api.OBPRestHelper$$anon$2.apply(OBPRestHelper.scala:190)
	at code.api.OBPRestHelper$$anon$3.apply(OBPRestHelper.scala:224)
	at code.api.OBPRestHelper$$anon$3.apply(OBPRestHelper.scala:220)
	at net.liftweb.http.rest.RestHelper$class.apply(RestHelper.scala:522)
	at code.api.v2_2_0.OBPAPI2_2_0$.apply(OBPAPI2_2_0.scala:44)
	at code.api.v2_2_0.OBPAPI2_2_0$.apply(OBPAPI2_2_0.scala:44)
	at net.liftweb.util.NamedPF$$anonfun$applyBox$1.apply(NamedPartialFunction.scala:97)
	at net.liftweb.util.NamedPF$$anonfun$applyBox$1.apply(NamedPartialFunction.scala:97)
	at net.liftweb.common.Full.map(Box.scala:610)
	at net.liftweb.util.NamedPF$.applyBox(NamedPartialFunction.scala:97)
	at net.liftweb.http.LiftServlet$$anonfun$1.apply$mcZ$sp(LiftServlet.scala:281)
	at net.liftweb.http.LiftServlet$$anonfun$1.apply(LiftServlet.scala:279)
	at net.liftweb.http.LiftServlet$$anonfun$1.apply(LiftServlet.scala:279)
	at net.liftweb.http.S$class.net$liftweb$http$S$$wrapQuery(S.scala:1470)
	at net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1$$anonfun$apply$37.apply(S.scala:1635)
	at net.liftweb.http.S$class.net$liftweb$http$S$$doAround(S.scala:1399)

**Comment by simonredfern** [comment]
Working now e.g. at https://apisandbox.openbankproject.com/obp/v2.2.0/message-docs/mar2017
